export const APIRoutes = {
  AUTH_LOGIN: '/auth/login',
  AUTH_REGISTER: '/auth/register',
  CREATE_CATEGORY: '/category/create-category',
  UPDATE_CATEGORY: '/category/update-category',
  GET_CATEGORIES: '/category/get-categories',
  DELETE_CATEGORY: '/category/delete-category',
  MAKE_ORDER: '/order/make-order',
  GET_ORDERS: '/order/get-orders',
  CANCEL_ORDER: '/order/cancel',
  GET_PRODUCTS: '/product/products',
  GET_PRODUCT_BY_ID: '/product/get',
  GET_PRODUCT_BY_CATEGORY: '/product/by-category',
  GET_MANY_PRODUCTS: 'product/get-many',
  GET_BY_CATEGORY: '/product/by-category',
  GET_USER_INFO: '/user/info',
  GET_ORDER_HISTORY: '/order/view-history/',
  SEARCH_PRODUCT_AND_CATEGORT: '/search/pro-and-cat',
  GET_NEW_ARRIVALS: '/product/arrivals',
  GET_DISCOUNT_PRODUCT: '/product/discount-product'
};
