export const APIRoutes = {
  AUTH_LOGIN: '/auth/login',
  AUTH_REGISTER: '/auth/register',
  CREATE_CATEGORY: '/category/create-category',
  UPDATE_CATEGORY: '/category/update-category',
  GET_CATEGORIES: '/category/get-categories',
  DELETE_CATEGORY: '/category/delete-category',
  MAKE_ORDER: '/order/make-order',
  GET_ORDERS: '/order/get-orders',
  CANCEL_ORDER: '/order/cancel',
  GET_PRODUCTS: '/product/products',
  GET_PRODUCT_BY_ID: '/product/get',
  GET_PRODUCT_BY_CATEGORY: '/product/by-category',
  GET_BY_CATEGORY: '/product/by-category',
};
